<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HomepageSetting extends Model
{
    protected $fillable = [
        'page_title',
        'company_name',
        'company_logo_url',
        'favicon_path',
        'operators_title',
        'operators_subtitle',
        'features_title',
        'features_subtitle',
        'feature1_title',
        'feature1_description',
        'feature2_title',
        'feature2_description',
        'feature3_title',
        'feature3_description',
        'feature4_title',
        'feature4_description',
        'stats_customers_label',
        'stats_customers_value',
        'stats_recharged_label',
        'stats_recharged_value',
        'stats_operators_label',
        'stats_operators_value',
        'stats_service_label',
        'stats_service_value',
        'footer_company_name',
        'footer_description',
        'footer_address',
        'footer_phone',
        'footer_email',
        'social_whatsapp_url',
        'social_youtube_url',
        'social_shopee_url',
        'social_telegram_url',
        'social_messenger_url',
        'mail_mailer',
        'mail_host',
        'mail_port',
        'mail_username',
        'mail_password',
        'mail_encryption',
        'mail_from_address',
        'mail_from_name',
        'sms_api_key',
        'sms_sender_id',
        'sms_api_url',
        'firebase_api_key',
        'firebase_auth_domain',
        'firebase_project_id',
        'firebase_storage_bucket',
        'firebase_messaging_sender_id',
        'firebase_app_id',
        'firebase_vapid_key',
        'firebase_service_account_json',
        'google_otp_enabled',
        'google_otp_issuer',
        'recaptcha_site_key',
        'recaptcha_secret_key',
        'tawk_property_id',
        'tawk_widget_id',
        'security_recaptcha',
        'security_ssl_https_redirect',
        'security_admin_login_captcha',
        'security_reseller_login_captcha',
        'security_pin_expire_days',
        'security_password_expire_days',
        'security_password_strong',
        'security_minimum_pin_length',
        'security_request_interval_minutes',
        'security_session_timeout_minutes',
        'security_support_ticket',
        'security_send_otp_via',
        'security_send_alert_via',
        'security_send_offline_sms_via',
        'security_bulk_flexi_limit',
        'security_auto_sending_limit',
        'security_reseller_overpayment_limit',
        'security_modem',
        'security_daily_limit',
        'security_gp',
        'security_robi',
        'security_banglalink',
        'security_airtel',
        'security_teletalk',
        'security_skitto',
        'security_popup_notice',
        'security_sms_sent_system',
        'security_bank_balance',
        'security_drive_balance',
        'security_balance_transfer',
        'security_commission_system',
    ];

    protected $casts = [
        'google_otp_enabled' => 'boolean',
        'security_pin_expire_days' => 'integer',
        'security_password_expire_days' => 'integer',
        'security_minimum_pin_length' => 'integer',
        'security_request_interval_minutes' => 'integer',
        'security_session_timeout_minutes' => 'integer',
        'security_bulk_flexi_limit' => 'integer',
        'security_auto_sending_limit' => 'integer',
        'security_daily_limit' => 'integer',
    ];
}
